export const ingredientsCategoriesArr = [
  {
    title: "Essentials",
    ingredientsArr: [
      "butter",
      "egg",
      "garlic",
      "milk",
      "onion",
      "sugar",
      "flour",
      "olive oil",
      "pepper",
      "carrot",
      "chicken",
      "oil",
      "rice",
      "cinnamon",
      "mayonnaise",
      "bread",
      "baking soda",
      "spaghetti",
      "tomato",
      "sour cream",
    ],
  },
  {
    title: "Vegetables",
    ingredientsArr: [
      "butter",
      "egg",
      "garlic",
      "milk",
      "onion",
      "sugar",
      "flour",
      "olive oil",
      "pepper",
      "carrot",
      "chicken",
      "oil",
      "rice",
      "cinnamon",
      "mayonnaise",
      "bread",
      "baking soda",
      "spaghetti",
      "tomato",
      "sour cream",
    ],
  },
  {
    title: "Vegetables",
    ingredientsArr: [
      "butter",
      "egg",
      "garlic",
      "milk",
      "onion",
      "sugar",
      "flour",
      "olive oil",
      "pepper",
      "carrot",
      "chicken",
      "oil",
      "rice",
      "cinnamon",
      "mayonnaise",
      "bread",
      "baking soda",
      "spaghetti",
      "tomato",
      "sour cream",
    ],
  },
];
